### ISSUE TITLE
Add service monitor manifest

### ISSUE THREAD

**Issue by rasheedamir** [stakater-charts/application#17]
Add service monitor and document as well

e.g.

```
{{- if .Values.servicemonitor.enabled -}}
{{- $port := .Values.service.port -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: {{ template "stakater-app.appname" . }}
    team: {{ required "A valid .Values.team entry required!" .Values.team }}
    app-version: {{ template "stakater-app.appversion" . }}
    chart: {{ template "stakater-app.chart" . }}
    heritage: {{ .Release.Service }}
    k8s-app: {{ template "stakater-app.appname" . }}
  name: {{ template "stakater-app.appname" . }}
  namespace: {{ .Values.servicemonitor.namespace }}
spec:
  endpoints:
  - interval: 10s
    path: /admin/prometheus
    port: {{ $port }}-tcp
    scheme: {{ .Values.service.scheme }}
    tlsConfig:
      insecureSkipVerify: true
  jobLabel: k8s-app
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: {{ template "stakater-app.appname" . }}
{{- end }}
```
