### ISSUE TITLE
Enforce resources requests & limits

### ISSUE THREAD

**Issue by rasheedamir** [stakater-charts/application#27]
Enforce requests & limits in the deployments

```
livenessProbe:
  initialDelaySeconds: 15
  timeoutSeconds: 5
  periodSeconds: 30
  successThreshold: 1
  failureThreshold: 5

readinessProbe:
  initialDelaySeconds: 15
  timeoutSeconds: 5
  periodSeconds: 30
  successThreshold: 1
  failureThreshold: 5
```
